config/routes.rb
Bptest::Application.routes.draw do

  resources :start
  resources :vols, :path => "VolumeIssue"
  resources :vol_jops, :path => "VolumeIssueJOP"
  resources :doilists, :path => "EmbargoPaP"
  resources :mycodes, :path => "podcast"
  resources :homerights, :path => "homeright" do
    resources :regulars do 
      resource :editorial
    end  
  end
  resources :subject_sets, :path => "SubjectCodesCheck"
  resources :doi_comparisons, :path => "DOICheck"

   root :to => 'start#index'

end

app/controllers/start_controller.rb
# -*- encoding : utf-8 -*-
 class StartController < ApplicationController

 def index

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @start }
    end
  end

end

app/views/start/index.html.erb
<h3 style="color:green" id="notice"><%= notice %></h3>
<p>&nbsp;</p>

<h2 align="center">ASCO Journals Team</h2><br>
<h4 align="center"><em>Some helpful web applications</em></h4>
<br>
<br>
<div align="center">
	<h4>Form Entry</h4>
	<%= link_to 'Early Release Embargo/PaP Date Entry', new_doilist_path %> |
	<%= link_to 'Volume/Issue Entry (JCO)', new_vol_path %> |
	<%= link_to 'Volume/Issue Entry (JOP)', new_vol_jop_path %>  
	<p>&nbsp;</p>
	
	<h4>Code Generation</h4>
	<%= link_to 'Podcast Code', mycodes_path %> |
	<%= link_to 'JCO Home-right Code', homerights_path %>
	<p>&nbsp;</p>

	<h4>QA Verification</h4>
	<%= link_to 'Early Release Article DOI Check', new_doi_comparison_path %> |
	<%= link_to 'Issue Subject Codes Check', 
		new_subject_set_path %>
</div>