config/routes.rb
Bptest::Application.routes.draw do

  resources :start
  resources :vols, :path => "VolumeIssue"
  resources :vol_jops, :path => "VolumeIssueJOP"
  resources :doilists, :path => "EmbargoPaP"
  resources :mycodes, :path => "podcast"
  resources :homerights, :path => "homeright" do
    resources :regulars do 
      resource :editorial
    end  
  end
  resources :subject_sets, :path => "SubjectCodesCheck"
  resources :doi_comparisons, :path => "DOICheck"

   root :to => 'start#index'

end

app/models/mycode.rb
# -*- encoding : utf-8 -*-
class Mycode < ActiveRecord::Base

end

app/controllers/mycodes_controller.rb
# -*- encoding : utf-8 -*-
class MycodesController < ApplicationController
  # GET /mycodes
  # GET /mycodes.json
 

  def index
    @mycodes = Mycode.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @mycodes }
    end
  end

  # GET /mycodes/1
  # GET /mycodes/1.json
  def show
    @mycode = Mycode.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @mycode }
    end
  end

  # GET /mycodes/new
  # GET /mycodes/new.json
  def new
    @mycode = Mycode.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @mycode }
    end
  end

  # GET /mycodes/1/edit
  def edit
    @mycode = Mycode.find(params[:id])
  end

  # POST /mycodes
  # POST /mycodes.json
  def create
    @mycode = Mycode.new(params[:mycode])



    respond_to do |format|
      if @mycode.save
        format.html { redirect_to @mycode, notice: 'Your code was successfully generated.' }
        format.json { render json: @mycode, status: :created, location: @mycode }
      else
        format.html { render action: "new" }
        format.json { render json: @mycode.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /mycodes/1
  # PUT /mycodes/1.json
  def update
    @mycode = Mycode.find(params[:id])

    respond_to do |format|
      if @mycode.update_attributes(params[:mycode])
        format.html { redirect_to @mycode, notice: 'Your code was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @mycode.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mycodes/1
  # DELETE /mycodes/1.json
  def destroy
    @mycode = Mycode.find(params[:id])
    @mycode.destroy

    respond_to do |format|
      format.html { redirect_to mycodes_url }
      format.json { head :no_content }
    end
  end
end

app/views/mycodes/_archiveandindexpage.html.erb
<%= "

<tr>
          <td>
            <center>
              <br />
              <img alt=\"jco-itunes-icon\" src=\"http://jco.ascopubs.org/site/podcasts/archive/jco-itunes-item-icon-sm.jpg\" /><br />
              #{@mycode.date.strftime('%B %d, %Y')}</center>
          </td>
          <td>
            <strong>#{@mycode.podtitle}</strong><br />
            <br />
            <em>By #{@mycode.speaker}</em><br />
            <br />

#{@mycode.wimpy}</object>

            <br />
            <br />
            <sup>(<a href=\"#{@mycode.podlink}?web\">Play/download file</a> - duration #{@mycode.duration.strftime('%M:%S')}, file size #{@mycode.mbsize.to_i} MB)</sup></td>
          <td>
            #{@mycode.artauthor} <a href=\"#{@mycode.artlink}\">[Abstract]</a></td>
        </tr>"     %> 

app/views/mycodes/_datasupp.erb
<%= "

<p>Copyright &#169; 2015 by the American Society of Clinical Oncology</p>

<p>Users can play the podcast directly in the audio player embedded below. If Flash is disabled on your browser, you can save the file directly to your computer or open on your mobile device by clicking on  \"Play/download file.\"  </p>

<p>
<strong>#{@mycode.podtitle} 

</strong><br/>
<I>By #{@mycode.speaker} </I><br/>
 
      #{@mycode.wimpy}</object>

<br/>
<br/>

(<a href=\"#{@mycode.podlink}?web\">Play/download file </a> - duration #{@mycode.duration.strftime('%M:%S')}, file size #{@mycode.mbsize.to_i} MB)

<p>This podcast presenter indicated no conflicts of interest.</p>"       %> 

app/views/mycodes/_form.html.erb
<%= form_for(@mycode) do |f| %>
  <% if @mycode.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mycode.errors.count, "error") %> prohibited this mycode from being saved:</h2>

      <ul>
      <% @mycode.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<br />
  <div class="field">
    <%= f.label 'Podcast title' %><br />
    <%= f.text_area :podtitle, :size => '100'  %>
  </div>
  <div class="field">
    <%= f.label 'Podcast author' %><br />
    <%= f.text_field :speaker, :size => '55' %>
  </div>
  <div class="field">
    <%= f.label 'Wimpy code' %><br />
    <%= f.text_area :wimpy, :size => '100' %>
  </div>
  <div class="field">
    <%= f.label 'Direct link to podcast' %><br />
    <%= f.text_area :podlink, :size => '100' %>
  </div>
  <div class="field">
    <%= f.label :duration %><br />
    <%= f.time_select :duration, :include_seconds => true %>
  </div>
  <div class="field">
    <%= f.label 'Size in megabytes' %><br />
    <%= f.text_field :mbsize, :size => '20' %>
  </div>
  <div class="field">    
    <%= f.label 'Size in bytes' %><br />
    <%= f.number_field :bytesize %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label 'Link to original article abstract' %><br />
    <%= f.text_area :artlink, :size => '100' %>
  </div>
  <div class="field">
    <%= f.label 'Article author' %><br />
    <%= f.text_field :artauthor, :size => '55' %>
  <div class="field">
    <%= f.label 'Description' %><br />
    <%= f.text_area :description, :size => '100' %>
  </div>
  <div class="field">
    <%= f.label 'Keywords' %><br />
    <%= f.text_area :keywords, :size => '100' %>
  </div>
  <div class="actions">
    <%= f.submit "Generate Podcast Code", :class => 'btn btn-primary' %>
  </div>
<% end %>
<p>&nbsp;</p>

app/views/mycodes/_issue.html.erb
<%="

<div class=\"podcast_container\" style=\"border-bottom:none;\">
					
					<div>


					<strong>#{@mycode.podtitle}</strong><br />
						<em>#{@mycode.speaker}</em>&nbsp;<font size=\"1\"> <a href=\"/site/podcasts/podcast-no-coi.xhtml\">[Disclosures]</a></font></div>
					<div style=\"text-align:center\">
						#{@mycode.wimpy}

</object>
</div>
					<div style=\"padding-bottom:5px\">
						<sub>#{@mycode.date.strftime('%B %d, %Y')} (#{@mycode.duration.strftime('%M:%S')}, #{@mycode.mbsize.to_i} MB) <a href=\"#{@mycode.podlink}\">play/download mp3</a></sub></div>
					<div>
						Related article: <b><a href=\"#{@mycode.artlink}\">#{@mycode.artauthor}</a></b></div>
				</div>
			"

%>

app/views/mycodes/_libsyn.html.erb
<div align="center">
<b>Title:</b> <%= @mycode.podtitle %><br>
<b>Subtitle:</b> <%= @mycode.podtitle %><br>
<b>Description:</b> <%= @mycode.description %><br>
<b>Permalink Points to:</b> Master Media File URL<br>
<b>Keywords:</b> <%= @mycode.keywords %><br>
<b>Advanced Options -> Extra Tags:</b> <%= %Q|<itunes:author>| %><%= @mycode.speaker %><%= %Q|</itunes:author>| %><br>
<b>Release Date:</b> <%= @mycode.date.strftime('%B %d, %Y') %> at 4:00 PM ET<br>
</div>

app/views/mycodes/_url.html.erb
<div align="center">

 

     
     <strong>Provided URL:</strong> <%= @mycode.podlink %><br>
     <strong>Generated URL by date:</strong> <%= "http://jco.ascopubs.org/site/podcasts/audio/#{@mycode.date.strftime('%Y')}/jcopodcast-#{@mycode.date.strftime('%m-%d-%Y')}.mp3" %><br>

</div>

app/views/mycodes/edit.html.erb
<div align="center">
<h2>Edit your code below</h2>
<%= link_to 'Back to your previous code', @mycode %> |
<%= link_to 'Podcasts Page', mycodes_path %> 


<%= render 'form' %>
</div>

app/views/mycodes/index.html.erb
<p>&nbsp;</p>
<div align="center">
<h2>Podcast Code Generator</h2>
<strong><%= link_to 'Generate new code here', new_mycode_path %></strong>
<h4>Previously Generated Code</h4>
<p>&nbsp;</p>

<table style="border:1px solid black;">
    <th>&nbsp;&nbsp;</th>
    <th>Speaker</th><th>&nbsp;&nbsp;&nbsp;&nbsp;</th>
    <th>Date</th>
<% @mycodes.each do |mycode| %>
    <tr>
 
<td>&nbsp;&nbsp;</td>       
<td><%= mycode.speaker %></td><td>&nbsp;&nbsp;&nbsp;&nbsp;</td>
 <td><%= mycode.date.strftime('%B %e, %Y') %></td><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<td>
<td><%= link_to 'Show', mycode %></td><td>&nbsp;</td>
<td><%= link_to 'Edit', edit_mycode_path(mycode) %></td><td>&nbsp;</td>
 <td><%= link_to 'Delete', mycode, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
    <% end %>
</table>

<br />
</div>

app/views/mycodes/new.html.erb
<p>&nbsp;</p>
<div align="center">
<h2>Podcast Code Generator</h2>
<%= link_to 'Podcasts Page', mycodes_path %>

<%= render 'form' %>
</div>

app/views/mycodes/show.html.erb
<br>
<div align="center">
<p id="notice"><%= notice %></p>

<h2>Your Podcast Code:</h2>
<%= link_to 'Edit this code', edit_mycode_path(@mycode) %> |
<%= link_to 'New code', new_mycode_path %> |
<%= link_to 'Podcasts Page', mycodes_path %> 

<h3>Podcast Data Supplement</h3>
</div>

<%=  render 'datasupp'   %>     

<br />
<br />

<h3 align="center">Podcast Index and Archive Pages</h3>

<%=  render 'archiveandindexpage' %>

<br />
<br />

<h3 align="center">Podcast URL</h3>

<%= render 'url' %>

<br />

<h3 align="center">Info for Libsyn</h3>

<%= render 'libsyn' %>

<br />

<h3 align="center">Issue Home-right Podcast Box</h3>

<%= render 'issue' %>

<br />
<br />
<br />
<div align="center">
<%= link_to 'Edit your input', edit_mycode_path(@mycode) %> |
<%= link_to 'Generate new podcast code', new_mycode_path %> 
</div>
<br />
<br />
<br />