config/routes.rb
Bptest::Application.routes.draw do

  resources :start
  resources :vols, :path => "VolumeIssue"
  resources :vol_jops, :path => "VolumeIssueJOP"
  resources :doilists, :path => "EmbargoPaP"
  resources :mycodes, :path => "podcast"
  resources :homerights, :path => "homeright" do
    resources :regulars do 
      resource :editorial
    end  
  end
  resources :subject_sets, :path => "SubjectCodesCheck"
  resources :doi_comparisons, :path => "DOICheck"

   root :to => 'start#index'

end

app/models/doi_comparison.rb
# -*- encoding : utf-8 -*-
class DoiComparison < ActiveRecord::Base
  attr_accessible :heather, :hwx
  #attr_accessor :flash_notice

def compare
#heatherArray = %w(heather)

self.heather = heather.strip.split(/[\s\n\r]+/).map{|cut| cut[1..4]}.sort

#hwxArray = %w(hwx)

self.hwx = hwx.strip.split(/[\s\n\r]+/).map{|cut| cut[-4..-1]}.sort

end

end

app/controllers/doi_comparisons_controller.rb
# -*- encoding : utf-8 -*-
class DoiComparisonsController < ApplicationController
  # GET /doi_comparisons
  # GET /doi_comparisons.json

  # GET /doi_comparisons/1
  # GET /doi_comparisons/1.json
  def show
    @doi_comparison = DoiComparison.find(params[:id])
 @doi_comparison.compare
 if @doi_comparison.heather == @doi_comparison.hwx
flash.now[:notice] = "These are a match!"
else
flash.now[:notice] = "There is a mismatch."
end 
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @doi_comparison }
    end
  end

  # GET /doi_comparisons/new
  # GET /doi_comparisons/new.json
  def new
    @doi_comparison = DoiComparison.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @doi_comparison }
    end
  end

  # GET /doi_comparisons/1/edit
  def edit
    @doi_comparison = DoiComparison.find(params[:id])
  end

  # POST /doi_comparisons
  # POST /doi_comparisons.json
  def create
    @doi_comparison = DoiComparison.new(params[:doi_comparison])
    if @doi_comparison.save
        redirect_to @doi_comparison 
      else
        format.html { render action: "new" }
        format.json { render json: @doi_comparison.errors, status: :unprocessable_entity }
      end
    end


  #if cutHeatherArray == cutHwxArray
   # flash[:notice] = "These are a match!"
  #else
  #  flash[:notice] = "There is a mismatch."
  #end
   # end
  #end

  # PUT /doi_comparisons/1
  # PUT /doi_comparisons/1.json
  def update
    @doi_comparison = DoiComparison.find(params[:id])

    respond_to do |format|
      if @doi_comparison.update_attributes(params[:doi_comparison])
        format.html { redirect_to @doi_comparison, notice: 'Doi comparison was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @doi_comparison.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doi_comparisons/1
  # DELETE /doi_comparisons/1.json
  def destroy
    @doi_comparison = DoiComparison.find(params[:id])
    @doi_comparison.destroy

    respond_to do |format|
      format.html { redirect_to doi_comparisons_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/doi_comparisons_helper.rb
# -*- encoding : utf-8 -*-
module DoiComparisonsHelper
end

app/views/doi_comparisons/_form.html.erb
<%= form_for(@doi_comparison) do |f| %>
  <% if @doi_comparison.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@doi_comparison.errors.count, "error") %> prohibited this doi_comparison from being saved:</h2>

      <ul>
      <% @doi_comparison.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label(:heather, t('Heather\'s list:')) %><br />
    <%= f.text_area :heather, :placeholder => "Paste in Heather's list here. All articles must be separated by spaces or new lines. They must also be five characters long, with the last four digits representing the last four digits of the DOI.                                For example: C9999" %>
  </div>

  <div class="field">
    <%= f.label(:hwx, t('HWX list:')) %><br />
    <%= f.text_area :hwx, :placeholder => "Paste in the list from HWX. All articles must be separated by either spaces or new lines. They must also be in their full DOI format.                                          For example: 10.1200/JCO.2013.99.9999" %>
  </div>
  <div class="actions">
    <%= f.submit "Compare these articles", :class => 'btn btn-primary' %>
  </div>

<% end %>

app/views/doi_comparisons/edit.html.erb
<div align="center">
<p>&nbsp;</p>
<h3>Edit your article comparison entries below</h3>

<%= render 'form' %>
</div>

app/views/doi_comparisons/new.html.erb
<div align="center">
<p>&nbsp;</p>
<h4>Verify the articles are the same by entering them below</h4>

<%= render 'form' %>
<p>&nbsp;</p><p>&nbsp;</p>
</div>

app/views/doi_comparisons/show.html.erb
<div align="center">
	<p>&nbsp;</p><p>&nbsp;</p>
<h4 id="notice"><%= notice %></h4><p>&nbsp;</p>

<p>
  <b>Heather:</b>
  <%= @doi_comparison.heather %>
</p>

<p>
  <b>HWX:</b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <%= @doi_comparison.hwx %>
</p>

<br>
<%= link_to 'Edit this entry', edit_doi_comparison_path(@doi_comparison) %> 
</div>