config/routes.rb
Bptest::Application.routes.draw do

  resources :start
  resources :vols, :path => "VolumeIssue"
  resources :vol_jops, :path => "VolumeIssueJOP"
  resources :doilists, :path => "EmbargoPaP"
  resources :mycodes, :path => "podcast"
  resources :homerights, :path => "homeright" do
    resources :regulars do 
      resource :editorial
    end  
  end
  resources :subject_sets, :path => "SubjectCodesCheck"
  resources :doi_comparisons, :path => "DOICheck"

   root :to => 'start#index'

end

app/models/homeright.rb
# -*- encoding : utf-8 -*-
class Homeright < ActiveRecord::Base
   attr_accessible :issuedate, :regulars_attributes

has_many :regulars
#has_many :editorials, :through => :regulars, :dependent => :destroy
accepts_nested_attributes_for :regulars, allow_destroy: true


end

app/controllers/homerights_controller.rb
# -*- encoding : utf-8 -*-
class HomerightsController < ApplicationController
  # GET /homerights
  # GET /homerights.json
  def index
    @homerights = Homeright.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @homerights }
    end
  end

  # GET /homerights/1
  # GET /homerights/1.json
  def show
    @homeright = Homeright.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @homeright }
    end
  end

  # GET /homerights/new
  # GET /homerights/new.json
  def new
   @homeright = Homeright.new
   
  #3.times do
   # regular = @homeright.regulars.build
   # 1.times  { regular.build_editorial }
  #end
  end

  # GET /homerights/1/edit
  def edit
    @homeright = Homeright.find(params[:id])
  end

  # POST /homerights
  # POST /homerights.json
  def create
    @homeright = Homeright.new(params[:homeright])

    respond_to do |format|
      if @homeright.save
        format.html { redirect_to @homeright, notice: 'Homeright was successfully created.' }
        format.json { render json: @homeright, status: :created, location: @homeright }
      else
        format.html { render action: "new" }
        format.json { render json: @homeright.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /homerights/1
  # PUT /homerights/1.json
  def update
    @homeright = Homeright.find(params[:id])

    respond_to do |format|
      if @homeright.update_attributes(params[:homeright])
        format.html { redirect_to @homeright, notice: 'Homeright was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @homeright.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homerights/1
  # DELETE /homerights/1.json
  def destroy
    @homeright = Homeright.find(params[:id])
    @homeright.destroy

    respond_to do |format|
      format.html { redirect_to homerights_url }
      format.json { head :no_content }
    end
  end
end

app/views/homerights/_bottom_of_issue.html.erb
 <%= "

					
<div style=\"font-size: 10px; margin-top:-15px;\">
				<a href=\"http://intl-jco.ascopubs.org/\">Alternate international access</a> <a href=\"http://jco.ascopubs.org/help/using/alternate-route\">[more info]</a></div>

			 "%>
					<br><br>
			<%= "
			<!-- END COVERLINES DIV //-->" %><br><br> 
			<%= "<!-- SPECIFIC PODCASTS go here --> "%>

app/views/homerights/_editorial_fields.html.erb
<fieldset class="offset1">
  <%= f.label :edauthor, "Editorial Author" %>
  <%= f.text_field :edauthor, :size => '55' %>
  
  <%= f.label :edlink, "Editorial Link" %>
  <%= f.text_field :edlink, :size => '55' %>

  <%= f.hidden_field :_destroy %>
  <%= link_to "remove", '#', class: "remove_fields" %>

</fieldset>

app/views/homerights/_form.html.erb
<%= form_for @homeright do |f| %>
  <% if @homeright.errors.any? %>
    <div class="error_messages">
      <h2><%= pluralize(@homeright.errors.count, "error") %> prohibited this code from being saved:</h2>
      <ul>
      <% @homeright.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<br>
Select the date of issue release:
<%= f.date_select :issuedate %>
<br>

<%= f.fields_for :regulars do |builder| %>
  <%= render 'regular_fields', f: builder %>
<% end %>

<%= link_to_add_fields "Add Article", f, :regulars %>
<p>&nbsp;</p>

<div class="actions">
    <%= f.submit "Generate Home_right Code", :class => 'btn btn-primary' %>
  </div>

<% end %>

app/views/homerights/_regular_fields.html.erb
<fieldset>
  <br/>
  <%= f.label :title, "Title" %><br />
  <%= f.text_field :title, :size => '100' %><br />
  
  <%= f.label :author, "Author" %><br />
  <%= f.text_field :author, :size => '60' %><br />
  
  <%= f.label :link, "Link" %><br />
  <%= f.text_field :link, :size => '60' %><br />
&nbsp;&nbsp;
  <%= f.hidden_field :_destroy %>
  <%= link_to "Remove this article", '#', class: "remove_fields" %>

<%= f.fields_for :editorials do |builder| %>
    <%= render 'editorial_fields', f: builder %>
  <% end %>

  <%= link_to_add_fields "Add related editorial", f, :editorials %>
<br/>
</fieldset>

app/views/homerights/_top.html.erb
 <%= "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">
<html xmlns=\"http://www.w3.org/1999/xhtml\" xmlns:hwui=\"http://schema.highwire.org/Site/UI\">
	<head>
		<title>Homepage Right Side</title>
		<!-- * Do not edit above this line; Edit title below: * -->
		<link href=\"/site/css/local_styles.css\" rel=\"proxy-stylesheet\" type=\"text/css\" />
		<!-- code for embedded WASP flash player--><script language=\"javascript\" src=\"wasp.js\"></script>
	</head>
	<body>
		<div id=\"begin-fragment-marker\">
			<!-- start of fragment marker div --></div>
		<div>
			<!-- end HW created block --><!-- * Begin editable area * -->
			<table>
				<tbody>
					<tr>
						<td colspan=\"2\">
							<a href=\"/content/early/recent\"><img src=\"/site/includefiles/early-release-button2.jpg\" /></a></td>
					</tr>
					<tr>
						<td colspan=\"2\">
							&nbsp;</td>
					</tr>
					<tr>
						<td colspan=\"2\">
							<h4>
								<a href=\"/content/current\">CURRENT ISSUE: MAY 10, 2013</a></h4>
						</td>
					</tr>
					<tr>
						<td colspan=\"2\">
							&nbsp;</td>
					</tr>
					<tr>
						<td colspan=\"2\">
							<b><u>HIGHLIGHTS</u></b></td>
					</tr> "  %>

app/views/homerights/edit.html.erb
<div align="center">
<h2>Edit your code below</h2>
<%= link_to 'Back to your previous code', @homeright %> | <%= link_to 'Home-right Page', homerights_path %> 
</div>

<%= render 'form' %>

<%= link_to 'Show', @homeright %> |
<%= link_to 'Back', homerights_path %>

app/views/homerights/index.html.erb
<div align="center">
<br />
<h2>Home-right Code Generator</h2>
<div><strong><%= link_to 'Generate new code here', new_homeright_path %></strong></div><br>
<h4>Previously Generated Code</h4><br>
<table style="border:1px solid black;">
  <tr>
    <th>&nbsp;&nbsp;</th>
    <th>Issue Date</th>
    <th>&nbsp;</th>
    <th>&nbsp;</th>
    <th>&nbsp;</th>
  </tr>

<% @homerights.each do |homeright| %>
  <tr>
    <td>&nbsp;</td>
    <td><%= "#{homeright.issuedate.strftime('%B %e, %Y')}" %></td><td>&nbsp;&nbsp;</td>
    <td><%= link_to 'Show', homeright %></td><td>&nbsp;</td>
    <td><%= link_to 'Edit', edit_homeright_path(homeright) %></td><td>&nbsp;</td>
    <td><%= link_to 'Remove', homeright, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>
<br />
</div>

app/views/homerights/new.html.erb
<p>&nbsp;</p>
<div class="container">

<div align="center">
<h2>Home_right Code Generator</h2>
<%= link_to 'Home-right Page', homerights_path %> 
</div>
<%= render 'form' %>

<%= link_to 'Back', homerights_path %>
</div>

app/views/homerights/show.html.erb
<div align="center"><p id="notice"><%= notice %></p>
<br />
<h3 align="center">Your Home_right code:</h3>
<%= link_to 'Edit this code', edit_homeright_path(@homeright) %> |
<%= link_to 'Home-right Page', homerights_path %> 
</div><br />
<br/>
<%=	"<!-- * Begin editable area * -->" %>
<br>

  <%=		"<div>
			<div id=\"home-right-top\">
				<div>
					<a href=\"/content/early/recent?home-right\"><img src=\"/site/includefiles/early-release-button2.jpg\" /></a></div>" %>
					<br />
					<br />
  <%=
					"<div id=\"current_issue\">
								<a href=\"/content/current?home-right\">CURRENT ISSUE HIGHLIGHTS: #{h@homeright.issuedate.strftime('%B %e, %Y')}</a></h4>
						</div>" %>
  <br />
  <br />
  <%=					"
							<!-- IF THERE IS A FEATURED SPECIAL ARTICLE 
					<div class=\"featured_box\">
							<strong>Featured Content</strong><br />
							<a href=\"http://jco.ascopubs.org/content/31/31/3997.abstract\"><em>ASCO Special Article</em>: Recommendations for Human Epidermal Growth Factor Receptor 2 Testing in Breast Cancer: ASCO/CAP Clinical Practice Guideline Update</a> <i>Wolff et al</i></div>
					
			
					 END OF FEATURED SPECIAL ARTICLE //--></div>" %>
					 <br />
					 <br />
  <%=
					"<div class=\"coverlines\"><!-- BEGIN COVERLINES DIV //-->
"%>
<br><br><%="<ul>" %><br>
<% @homeright.regulars.each do |regular| %>

<%=  "<li>
							<a href=\"#{regular.link}\">#{regular.title}</a> <i>#{regular.author}</i></li>
					" %>
<br />

<% regular.editorials.each do |editorial| %>

<%= 

 					"<li class=\"editorial\" style=\"margin:-8px 0px 0px 20px\"> <a href=\"#{editorial.edlink}\">Editorial:</a> <i>#{editorial.edauthor}</i></li>
					" %>

<br />
<% end %>
<% end %>
<%= "</ul>" %>
<br />
<br>
<%= render 'bottom_of_issue' %>

<br />
<br />